### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by xguitoux** [DavidBabel/Switch-Backup-Rename#2]
Salut j'ai l'erreur suivante lorsque j'exécute ton soft directement dans ma SD card (Exec windows)

 at sanitizeSerial (C:\snapshot\Switch-Backup-Rename\utils\filter-helpers.js:0:0)
    at getCurrentGameInfo (C:\snapshot\Switch-Backup-Rename\utils\filter-helpers.js:0:0)
    at getGamesInfos.then.fs.readdirSync.forEach.file (C:\snapshot\Switch-Backup-Rename\_switch-backup-rename.js:0:0)
    at Array.forEach (<anonymous>)
    at getGamesInfos.then.gamesInfos (C:\snapshot\Switch-Backup-Rename\_switch-backup-rename.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1308:13)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

Merci pour ton aide

**Comment by DavidBabel** [comment]
Peux tu me fournir la liste des fichiers présent dans ton dossier ?

**Comment by DavidBabel** [comment]
Le nom du fichier doit contenir le title id du jeu pour qu'il puisse les renommer proprement. Actuellement http://nswdb.com/ d'où je tire le nom des releases est down. Je pense que le script est hs pendant ce temps.

**Comment by DavidBabel** [comment]
fixed with new release https://github.com/DavidBabel/Switch-Backup-Rename/releases
